version: '3'
services:
  docker-compoose-node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "docker-compoose-node-app"
    command: npm start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mongo-docker

  mongo-docker:
    image: mongo:4.4.6
    container_name: "mongo-docker"
    volumes:
      - ./data:/data/db
      - ./:/app
    ports:
      - 27017:27017
    environment:
      - MONGO_HOST=mongo

